package nexus

import (
	"time"
)

// StartOperationOptions are options for the StartOperation client and server APIs.
type StartOperationOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	//
	// Header keys with the "content-" prefix are reserved for [Serializer] headers and should not be set in the
	// client API; they are not available to server [Handler] and [Operation] implementations.
	Header Header
	// Callbacks are used to deliver completion of async operations.
	// This value may optionally be set by the client and should be called by a handler upon completion if the started operation is async.
	//
	// Implement a [CompletionHandler] and expose it as an HTTP handler to handle async completions.
	CallbackURL string
	// Optional header fields set by a client that are required to be attached to the callback request when an
	// asynchronous operation completes.
	CallbackHeader Header
	// Request ID that may be used by the server handler to dedupe a start request.
	// By default a v4 UUID will be generated by the client.
	RequestID string
	// Links contain arbitrary caller information. Handlers may use these links as
	// metadata on resources associated with and operation.
	Links []Link
}

// TransportStartOperationOptions are options for [Transport.StartOperation].
//
// NOTE: Experimental
type TransportStartOperationOptions struct {
	// Options passed to [Client.StartOperation].
	ClientOptions StartOperationOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
}

// ExecuteOperationOptions are options for [Client.ExecuteOperation].
//
// NOTE: Experimental
type ExecuteOperationOptions struct {
	// Callback URL to provide to the handle for receiving async operation completions. Optional.
	// Even though Client.ExecuteOperation waits for operation completion, some applications may want to set this
	// callback as a fallback mechanism.
	CallbackURL string
	// Optional header fields set by a client that are required to be attached to the callback request when an
	// asynchronous operation completes.
	CallbackHeader Header
	// Request ID that may be used by the server handler to dedupe this start request.
	// By default a v4 UUID will be generated by the client.
	RequestID string
	// Links contain arbitrary caller information. Handlers may use these links as
	// metadata on resources associated with and operation.
	Links []Link
	// Header to attach to start and get-result requests. Optional.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	//
	// Header keys with the "content-" prefix are reserved for [Serializer] headers and should not be set in the
	// client API; they are not available to server [Handler] and [Operation] implementations.
	Header Header
	// Duration to wait for operation completion.
	//
	// ⚠ NOTE: unlike GetOperationResultOptions.Wait, zero and negative values are considered effectively infinite.
	Wait time.Duration
}

// GetOperationResultOptions are options for the GetOperationResult client and server APIs.
//
// NOTE: Experimental
type GetOperationResultOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
	// If non-zero, reflects the duration the caller has indicated that it wants to wait for operation completion,
	// turning the request into a long poll.
	Wait time.Duration
}

// TransportGetOperationResultOptions are options for [Transport.GetOperationResult].
//
// NOTE: Experimental
type TransportGetOperationResultOptions struct {
	// Options passed to [OperationHandle.GetResult].
	ClientOptions GetOperationResultOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}

// GetOperationInfoOptions are options for the GetOperationInfo client and server APIs.
//
// NOTE: Experimental
type GetOperationInfoOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
}

// TransportGetOperationInfoOptions are options for [Transport.GetOperationInfo].
//
// NOTE: Experimental
type TransportGetOperationInfoOptions struct {
	// Options passed to [OperationHandle.GetInfo].
	ClientOptions GetOperationInfoOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}

// CancelOperationOptions are options for the CancelOperation client and server APIs.
type CancelOperationOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
}

// TransportCancelOperationOptions are options for [Transport.CancelOperation].
//
// NOTE: Experimental
type TransportCancelOperationOptions struct {
	// Options passed to [OperationHandle.Cancel]
	ClientOptions CancelOperationOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}

// CompleteOperationOptions are options for the CompleteOperation client and server APIs.
//
// NOTE: Experimental
type CompleteOperationOptions struct {
	// Header to send in the completion request.
	Header Header

	// Result of the operation. Indicates a successful completion. Mutually exclusive with Error.
	Result any

	// Error produced by the operation. Indicates an operation failure. Mutually exclusive with Result.
	Error *OperationError

	// OperationToken is the unique token for this operation. Used when a completion callback is received before a
	// started response.
	OperationToken string
	// StartTime is the time the operation started. Used when a completion callback is received before a started response.
	StartTime time.Time
	// Links are used to link back to the operation when a completion callback is received before a started response.
	Links []Link
}

// TransportCompleteOperationOptions are options for [Transport.CompleteOperation]
//
// NOTE: Experimental
type TransportCompleteOperationOptions struct {
	// Options passed to [CompletionClient.CompleteOperation]
	ClientOptions CompleteOperationOptions
	// State of the operation, should be succeeded, failed, or canceled.
	State OperationState
	// URL indicating the destination where the completion should be delivered.
	URL string
}
