package nexus

import (
	"time"
)

// StartOperationOptions are options for the StartOperation client and server APIs.
type StartOperationOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	//
	// Header keys with the "content-" prefix are reserved for [Serializer] headers and should not be set in the
	// client API; they are not available to server [Handler] and [Operation] implementations.
	Header Header
	// Callbacks are used to deliver completion of async operations.
	// This value may optionally be set by the client and should be called by a handler upon completion if the started operation is async.
	//
	// Implement a [CompletionHandler] and expose it as an HTTP handler to handle async completions.
	CallbackURL string
	// Optional header fields set by a client that are required to be attached to the callback request when an
	// asynchronous operation completes.
	CallbackHeader Header
	// Request ID that may be used by the server handler to dedupe a start request.
	// By default a v4 UUID will be generated by the client.
	RequestID string
	// Links contain arbitrary caller information. Handlers may use these links as
	// metadata on resources associated with and operation.
	Links []Link
}

// TransportStartOperationOptions are options for [Transport.StartOperation].
//
// NOTE: Experimental
type TransportStartOperationOptions struct {
	// Options passed to [ServiceClient.StartOperation].
	ClientOptions StartOperationOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
}

// ExecuteOperationOptions are options for [ServiceClient.ExecuteOperation].
//
// NOTE: Experimental
type ExecuteOperationOptions struct {
	// Callback URL to provide to the handle for receiving async operation completions. Optional.
	// Even though ServiceClient.ExecuteOperation waits for operation completion, some applications may want to set this
	// callback as a fallback mechanism.
	CallbackURL string
	// Optional header fields set by a client that are required to be attached to the callback request when an
	// asynchronous operation completes.
	CallbackHeader Header
	// Request ID that may be used by the server handler to dedupe this start request.
	// By default a v4 UUID will be generated by the client.
	RequestID string
	// Links contain arbitrary caller information. Handlers may use these links as
	// metadata on resources associated with and operation.
	Links []Link
	// Header to attach to start and get-result requests. Optional.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	//
	// Header keys with the "content-" prefix are reserved for [Serializer] headers and should not be set in the
	// client API; they are not available to server [Handler] and [Operation] implementations.
	Header Header
	// Duration to wait for operation completion.
	//
	// ⚠ NOTE: unlike FetchOperationResultOptions.Wait, zero and negative values are considered effectively infinite.
	Wait time.Duration
}

// FetchOperationResultOptions are options for the FetchOperationResult client and server APIs.
//
// NOTE: Experimental
type FetchOperationResultOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
	// If non-zero, reflects the duration the caller has indicated that it wants to wait for operation completion,
	// turning the request into a long poll.
	Wait time.Duration
}

// TransportFetchOperationResultOptions are options for [Transport.FetchOperationResult].
//
// NOTE: Experimental
type TransportFetchOperationResultOptions struct {
	// Options passed to [OperationHandle.FetchResult].
	ClientOptions FetchOperationResultOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}

// FetchOperationInfoOptions are options for the FetchOperationInfo client and server APIs.
//
// NOTE: Experimental
type FetchOperationInfoOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
}

// TransportFetchOperationInfoOptions are options for [Transport.FetchOperationInfo].
//
// NOTE: Experimental
type TransportFetchOperationInfoOptions struct {
	// Options passed to [OperationHandle.FetchInfo].
	ClientOptions FetchOperationInfoOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}

// CancelOperationOptions are options for the CancelOperation client and server APIs.
type CancelOperationOptions struct {
	// Header contains the request header fields either received by the server or to be sent by the client.
	//
	// Header will always be non empty in server methods and can be optionally set in the client API.
	//
	// Header values set here will overwrite any SDK-provided values for the same key.
	Header Header
}

// TransportCancelOperationOptions are options for [Transport.CancelOperation].
//
// NOTE: Experimental
type TransportCancelOperationOptions struct {
	// Options passed to [OperationHandle.Cancel]
	ClientOptions CancelOperationOptions
	// Service name. Required.
	Service string
	// Operation name. Required.
	Operation string
	// Token for the operation as generated by the operation handler. Required.
	Token string
}
