name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Install tool dependencies
        run: go install $(go list -f '{{join .Imports " "}}' tools.go)
        working-directory: ./tools
      - name: Test
        run: go test -v  $(go list -f '{{.Dir}}/...' -m | xargs)
      - name: Lint
        run: golangci-lint run -v  $(go list -f '{{.Dir}}/...' -m | xargs)
