name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-lint-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --verbose --timeout 3m --fix=false
      - name: Test
        run: go test -v  ./...
      - name: Lint nexusproto
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
          args: --verbose --timeout 3m --fix=false
          working-directory: ./contrib/nexusproto
      - name: Test nexusproto
        run: go test -v  ./...
        working-directory: ./contrib/nexusproto
